language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: vIsrJ8GX4xCS7EI5nAuL8APPMBah6dVu3zsv1+sWAaqZWwied+kpBOW24OQGglJFVAVGJN1fEFQ/IstMpLyxcZHhtrkfcVL5NV/c2dTnhMHEj9D6s1L1/K6wgHQ26puaCoa8f6SBN9yA4m5vowbSz5B48Wa5cqRnZ58V162o5jo8JYO1gKWsiy16nnhZO24P/ZrYDBPFEPS+uFAk9PkdEyD0sC7h4BmtAsnT6oySiZb50h/oQHdiKu0LhfV8lfzp0tnz+n1/FSl7Fc7b0U38ASA6ZIkUyLkLloiUIC0oeP/WKQVoIcU6FjVdZDrMGFIsX4FJ/uDfRDJwrscWHqVlrGexO8Pvy+L2hrSlp70lW+X8A2u/IvLF1crSBdIOf/fQ+NP8ArECoKYOATVNXEv10L4sC0long84IalaYKofxKYRzRj0tTQYXHIrwGouLL2UHbSsuxHl1qz0uJPXueAuOODJGn/ftK6Dg+S1TMwjoKMXlN/OE4P2SZ4BlvfKWf3PkBMyzNhUip0py7wAV44lFkJk0Ahxk2mFPuw8O0hze1luODjxh1CdjcCBPn2hMzoWxGlXtFxpJzHrR7Bl+1OTSjWiPmUBZqRaa8TFjmTD+wpekCojtJXFB3MfEeq1QU/jih14NgiGX2HVHqa/zsGk1k5H9RaXmSS5J2oBjPuyyN0=
  app: mxlist
  on:
    repo: taypsl/mx-list
